<a href="https://colab.research.google.com/github/lstiffl2-pixel/Sketch4/blob/main/sketch04_Stiffler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
%pip install -q libpysal esda splot mapclassify contextily

In [27]:
import pandas as pd

DATA_BASE = "https://raw.githubusercontent.com/pjbitterman/KSU_x9076/main/data"
oh_precip = pd.read_csv(f"{DATA_BASE}/part1/ohio_precip_2025.csv")
oh_precip.head()

    station_id               name      lat      lon  precip_mm_2025
0  US1OHAB0021  ASHTABULA 1.8 NNE  41.9037 -80.7829           910.4
1  US1OHAD0005       SEAMAN 3.4 E  38.9399 -83.5090          1270.7
2  US1OHAD0006      PEEBLES 4.2 N  39.0075 -83.4146          1174.8
3  US1OHAL0005        LIMA 2.7 NE  40.7739 -84.0800           904.3
4  US1OHAL0008    DELPHOS 2.3 ESE  40.8335 -84.2982           711.4

In [28]:
oh_precip["precip_mm_2025"].describe()

count     410.000000
mean     1008.862439
std       174.937689
min       350.900000
25%       895.575000
50%      1014.050000
75%      1125.500000
max      1495.700000
Name: precip_mm_2025, dtype: float64

In [37]:
top_5= oh_precip.sort_values("precip_mm_2025", ascending=False).head(5)[["name", "precip_mm_2025"]]
top_5.head()

                              name  precip_mm_2025
406  CINCINNATI MUNI AP LUNKEN FLD          1495.7
228                 SHELBY 0.6 NNE          1488.7
16                  ATHENS 4.6 ESE          1431.6
108             MIDDLEFIELD 0.6 NE          1411.7
48                   MIDLAND 2.9 S          1402.5

In [54]:
dist_from_mean= top_5.head(1)["precip_mm_2025"]-oh_precip["precip_mm_2025"].mean()
print(dist_from_mean)

406    486.837561
Name: precip_mm_2025, dtype: float64

The wettest station (1495.7mm) has 486.837561mm more rain than the mean precipitation amount (1008.862439mm). This seems like a significant difference especially considering that the maximum value is over 2 standared deviations away from the mean which makes it an unusual value.